spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/test
    username: testuser
    password: testuser
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}
    locations: classpath:db/migration
    schemas: springtest
