spring:
  profiles:
    active: local-dev
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
    show-sql: true

---
spring:
  profiles: integration-test
  flyway:
    locations: classpath:db/migration, classpath:db/integration-test

---
spring:
  profiles: local-dev
  datasource:
    # User has to have GRANT CREATE EXTENSION for script execution
    url: jdbc:postgresql://bblaccount:5432/bbl
    username: bbladmin
    password: postgres
  flyway:
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}
    locations: classpath:db/migration
