spring:
  profiles:
    active: local-dev
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
app:
  jwt:
    secret: test@secret
    expiration: 86400000
    header: Authorization
    prefix: Bearer
  token:
    email:
      verification:
        duration: 3600000
    password:
      reset:
        duration: 3600000
    refresh:
      duration: 2592000000
  velocity:
    templates:
      location: /templates/
---
spring:
  profiles: integration-test
  flyway:
    locations: classpath:db/migration, classpath:db/integration-test

---
spring:
  profiles: local-dev
  datasource:
    # User has to have GRANT CREATE EXTENSION for script execution
    url: jdbc:postgresql://localhost:1717/bbl
    username: bbl
    password: bbl
  flyway:
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}
    locations: classpath:db/migration
